version: "3.8"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASS
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
  backend:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - node_net
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - node_net
    depends_on:
      - backend
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
